### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by KindaMe** [KindaMe/iracing-season-planner#3]
# todo-list
### Stats
- [ ] More stats with better algorithms
### Manage
- [ ] Prices of all items and more stats based on that
- [ ] Images of all tracks and cars
- [ ] Usefull info about each item
### Updates
- [ ] Auto update feature
